name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code of ${{ github.repository }}
        uses: actions/checkout@v3
      - name: Update the docker image
        run: |
          docker login --username ${{ secrets.DOCKER_USER }} --password ${{ secrets.DOCKER_PASS }}
          docker image build -t andresnboza/reload-app-server .
          docker push andresnboza/reload-app-server
      - run: echo "🍏 This job's status is ${{ job.status }}."
